btmenu: Actually check if we succeeded
The previous checks were known to usually be insufficient. There's now
an attempt to later verify we actually connected.

diff --git a/btmenu b/btmenu
--- a/btmenu
+++ b/btmenu
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 _bluetoothctl() {
-    timeout 30 bluetoothctl
+    LC_ALL=C timeout 30 bluetoothctl
 }
 
 mode=connect
@@ -35,12 +35,21 @@ execute_mode() {
     local name
     local mac
     local preposition
+    local expected_to_connect
+    local retries
 
     mode=${1?BUG: missing mode}
+    retries=5
 
     case $mode in
-        connect) preposition=to ;;
-        disconnect) preposition=from ;;
+        connect)
+            preposition=to
+            expected_to_connect=yes
+        ;;
+        disconnect)
+            preposition=from
+            expected_to_connect=no
+        ;;
     esac
 
     if ! (( ${#DEVICES[@]} )); then
@@ -52,13 +61,29 @@ execute_mode() {
     [[ $name ]] || return
     mac=${DEVICES["$name"]}
 
-    if printf 'power on\n%s %s\n' "$mode" "$mac" | _bluetoothctl; then
-        notify "${mode^}ed $preposition $name"
-    else
+    if ! printf 'power on\n%s %s\n' "$mode" "$mac" | _bluetoothctl; then
+        # Usually we fail later when the timeout is reached, but this means
+        # something probably went wrong in the earlier stages.
         ret="$?"
         notify "Failed to $mode $preposition $name" 1
         return "$ret"
     fi
+
+    notify "Attempting to $mode $preposition $name" 1
+
+    while (( retries-- )); do
+        if printf 'info %s\n' |
+            _bluetoothctl |
+            grep -q '^[\t ]\+Connected: '"$expected_to_connect"; then
+            notify "${mode^}ed $preposition $name"
+            return 0
+        fi
+        sleep 1
+    done
+
+    ret="$?"
+    notify "Failed to $mode $preposition $name" 1
+    return "$ret"
 }
 
 i=2
